datadog:
  apiKeyExistingSecret: datadog-secret
  aappKeyExistingSecret: datadog-secret
  clusterName: $CLUSTER_NAME
  env:
    - name: DD_APM_FEATURES
      value: 'enable_cid_stats'

  logs:
    enabled: true
    containerCollectAll: true
  apm:
    socketEnabled: true
    portEnabled: true

  processAgent:
    enabled: true
    processCollection: true

  # Enable the new `kubernetes_state_core` check.
  kubeStateMetricsCore:
    enabled: true
  # Avoid deploying kube-state-metrics chart.
  # The new `kubernetes_state_core` doesn't require to deploy the kube-state-metrics anymore.
  kubeStateMetricsEnabled: false

clusterAgent:
  enabled: true
  metricsProvider:
    enabled: true
     
agents:
  containers:
    agent:
      # resources for the Agent container
      resources:
        requests:
          cpu: 200m
          memory: 256Mi

    traceAgent:
      # resources for the Trace Agent container
      resources:
        requests:
          cpu: 100m
          memory: 200Mi

    processAgent:
      # resources for the Process Agent container
      resources:
        requests:
          cpu: 100m
          memory: 200Mi

  priorityClassCreate: true

providers:
  gke:
    autopilot: true
