targetSystem: "linux"
datadog:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  clusterName: <GKE Autopilot Cluster name>
  site: datadoghq.com
  logLevel: INFO
  clusterChecks:
    # datadog.clusterChecks.enabled -- Enable the Cluster Checks feature on both the cluster-agents and the daemonset
    enabled: true
    # datadog.clusterChecks.shareProcessNamespace -- Set the process namespace sharing on the cluster checks agent
    shareProcessNamespace: false
  tags: 
    - env:envtag
    - datadog:monitored
 
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    portEnabled: true
    port: 8126 # default
  processAgent:
    enabled: true
    processCollection: true
  # Enable the new `kubernetes_state_core` check.
  kubeStateMetricsCore:
    enabled: true
  # Avoid deploying kube-state-metrics chart.
  # The new `kubernetes_state_core` doesn't require to deploy the kube-state-metrics anymore.
  kubeStateMetricsEnabled: false

  confd:
    apache.yaml: |-
      ad_identifiers:
        - <CONTAINERNAME>
      init_config:
      instances:
        - apache_status_url: "http://%%host%%/server-status?auto"
      tls_verify: false
      logs:
        - type: file
          path: /var/log/apache2/access.log
          service: apache
          source: apache
        - type: file
          path: /var/log/apache2/error.log
          service: apache
          source: apache

clusterAgent:
  admissionController:
    enabled: true
    replicas: 2
  metricsProvider:
    enabled: true
     
agents:
  containers:
    agent:
      # resources for the Agent container
      resources:
        requests:
          cpu: 200m
          memory: 256Mi

    traceAgent:
      # resources for the Trace Agent container
      resources:
        requests:
          cpu: 100m
          memory: 200Mi

    processAgent:
      # resources for the Process Agent container
      resources:
        requests:
          cpu: 100m
          memory: 200Mi

  priorityClassCreate: true

providers:
  gke:
    autopilot: true
